/**
 * Written by Gideon Pfeffer
 * sets up the XML reader for all sub classes
 */
package XMLReads;

import java.util.Random;

import cellsociety_team06.ReadXMLFile;

public class Reads{
	private ReadXMLFile files;
	private String type;
	private int size;
	private int inputStyle;
	private int simType;
	private Random rand;

	/**
	 * reads the XML file based on the string and size
	 */
	public Reads(String type, int is, int st){
		this.type = type;
		files = new ReadXMLFile();
		inputStyle = is;
		simType = st;
	}

	/**
	 * returns the character at that index
	 * of the map generated by the XML reader
	 */
	public Character get(int i, int j){
		if (inputStyle == 1){
			return files.returnMap().get(type).get(i).get(j);
		} else {
			return randomChar();
		}
	}
	
	private Character randomChar(){
		
		if (simType == 1){
			if(rand.nextInt(100) < 50){ //percent chance of this block
				return '0';
			}
			else{
				return 'L';
			}
		} else if (simType == 2){
			return 'G';
		} else if (simType == 3){
			if(rand.nextInt(100) < 100/3){ //percent chance of this block
				return '0';
			} else if (rand.nextInt(100) < 100/3){
				return 'Y';
			} else {
				return 'R';
			}
		} else if (simType == 4){
			if(rand.nextInt(100) < 100/3){ //percent chance of this block
				return 'A';
			} else if (rand.nextInt(100) < 100/3){
				return 'B';
			} else {
				return '0';
			}
		} else {
			if(rand.nextInt(100) < 50){ //percent chance of this block
				return 'A';
			}
			else{
				return 'S';
			}
		}
	}

	/**
	 * @returns the size of the map generated by the XML
	 */
	public int size(){
		return size;
	}
	
	/**
	 * @returns the height of the xml generated map
	 */
	public int height(){
		return files.returnMap().get(type).size();
	}

	/**
	 * @returns the width of the xml generated map
	 */
	public int width(){
		return files.returnMap().get(type).get(0).size();
	}

}
